### PR TITLE
feat(geth): change CORS config, metamask, add other items

### PR DESCRIPTION
**Pull request by ryanio**
#### What does it do?
Adds a settings field called `Profile` that passes in flags `--rpc --rpccorsdomain moz-extension://e582a415-cf54-468e-9b4b-f32b576f7bf7,chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn`

Screen Shot 2019-04-25 at 10 07 43 AM
Screen Shot 2019-04-25 at 10 07 56 AM

UI considerations:
1. Ideally, after selecting, it would explain to the user how to switch MetaMask to the local node:
Screen Shot 2019-04-25 at 10 30 21 AM

Closes https://github.com/ethereum/grid/pull/190, https://github.com/ethereum/grid/pull/357

### CODE REVIEW

**Comment by evertonfraga** [comment]
It generates the flags accordingly. My light sync hasn't connected to enough peers yet, so I can't ensure it's working properly ;)

**Comment by marcgarreau** [comment]
⚠️ blocked by https://github.com/MetaMask/metamask-extension/issues/6580

**Comment by evertonfraga** [comment]
Closes https://github.com/ethereum/grid/pull/190

**Comment by evertonfraga** [comment]
closes #357

**Pull request merged**
